### ISSUE TITLE
npm package problems

### ISSUE THREAD

**Issue by selfagency** [devenvyas/redis-cache-express#2]
Can't install with Yarn or NPM presently

```
❯ yarn add redis-express-cache                                                                                           2s 301ms
yarn add v1.3.2
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "redis-express-cache" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
❯ npm install redis-express-cache                                                                                        2s 641ms
npm ERR! code E404
npm ERR! 404 Not Found: redis-express-cache@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2018-01-18T17_44_07_014Z-debug.log
```

```
❯ cat /Users/daniel/.npm/_logs/2018-01-18T17_44_07_014Z-debug.log                                                        8s 675ms
0 info it worked if it ends with ok
1 verbose cli [ '/Users/daniel/.nvm/versions/node/v8.4.0/bin/node',
1 verbose cli   '/Users/daniel/.nvm/versions/node/v8.4.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'redis-express-cache' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose npm-session 39d98a40c4c475d5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/redis-express-cache 1519ms
8 silly fetchPackageMetaData error for redis-express-cache@latest 404 Not Found: redis-express-cache@latest
9 verbose stack Error: 404 Not Found: redis-express-cache@latest
9 verbose stack     at fetch.then.res (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
9 verbose stack     at tryCatcher (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/Users/daniel/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
10 verbose cwd /Users/daniel/Dev/nylon-web
11 verbose Darwin 17.3.0
12 verbose argv "/Users/daniel/.nvm/versions/node/v8.4.0/bin/node" "/Users/daniel/.nvm/versions/node/v8.4.0/bin/npm" "install" "redis-express-cache"
13 verbose node v8.4.0
14 verbose npm  v5.3.0
15 error code E404
16 error 404 Not Found: redis-express-cache@latest
17 verbose exit [ 1, true ]
```

**Comment by selfagency** [comment]
unfortunately, i had to switch to a different package b/c i couldn't get this one to install. but it is working now.
